#+DRAWERS: NOEXPORT
#+OPTIONS: d:(not "NOEXPORT")
* org-doc

:NOEXPORT:
[[http://www.gnu.org/licenses/gpl-3.0.txt][https://img.shields.io/badge/license-GPL_3-green.svg]]
[[https://travis-ci.org/smaximov/org-doc][https://travis-ci.org/smaximov/org-doc.svg?branch=master]]
[[https://coveralls.io/github/smaximov/org-doc?branch=master][https://coveralls.io/repos/github/smaximov/org-doc/badge.svg?branch=master]]
:END:

=org-doc= — generate conventional [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][library headers]] from Org mode files.

** Installation

FIXME: to be written.

** Usage

tl;dr (assuming you're using [[https://github.com/cask/cask][Cask]] for project management)

1. Add =org-doc= to the development dependencies of your library:

   #+begin_src lisp
     (development
      (depends-on "org-doc"))
   #+end_src

   Fetch dependencies:

   #+begin_src bash
     $ cask install
   #+end_src

2. Put the [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][library header]] boilerplate in your ELisp file.

3. Generate /Commentary/ section of the library headers:

   #+begin_src bash
     $ cask emacs --batch -l org-doc-cli -f org-doc -- \
         README.org your-package.el
   #+end_src

4. [Optional] Generate /Change Log/ section of the library headers:

   #+begin_src bash
     $ cask emacs --batch -l org-doc-cli -f org-doc -- \
         --section changelog CHANGELOG.org your-package.el
   #+end_src

5. Commit.

Run ~cask emacs --batch -l org-doc-cli -f org-doc -- --help~ to see
available options.

*** Inside Emacs

First you need to load =org-doc=:

#+begin_src elisp
  (require 'org-doc)
#+end_src

Then you can interactively call =org-doc:update-file-header=.

*** From the command line

FIXME: to be written.

** Contributing                                                    :noexport:

*** Prerequisites

You need [[https://github.com/cask/cask][Cask]] installed (see [[http://cask.readthedocs.io/en/latest/guide/installation.html][docs]]).

*** Setup

Clone the repository:

#+begin_src bash
  $ git clone git@github.com:smaximov/org-doc.git
#+end_src

Install dependencies:

#+begin_src bash
  $ make dep-update
#+end_src

*** Preparing a pull request

Make sure all tests pass:

#+begin_src bash
  $ make test
#+end_src

Update package's commentary header if you have made changes to [[file:README.org][README.org]] (do not edit commentary by hand!):

#+begin_src bash
  $ make update-headers
#+end_src

Commit final changes and create a pull request, describing briefly what it does.

** Similar projects

- [[https://github.com/cute-jumper/org2elcomment][org2elcomment]] (available on MELPA).

** License                                                         :noexport:

This program is distributed under the terms of GNU General Public License,
version 3 or any later version. See [[file:COPYING][COPYING]] for details.
