#+DRAWERS: NOEXPORT
#+OPTIONS: d:(not "NOEXPORT")
* org-doc

:NOEXPORT:
[[http://www.gnu.org/licenses/gpl-3.0.txt][https://img.shields.io/badge/license-GPL_3-green.svg]]
[[https://travis-ci.org/smaximov/org-doc][https://travis-ci.org/smaximov/org-doc.svg?branch=master]]
[[https://coveralls.io/github/smaximov/org-doc?branch=master][https://coveralls.io/repos/github/smaximov/org-doc/badge.svg?branch=master]]
:END:

=org-doc= — generate or update conventional [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][library headers]] using Org mode files.

** Why?

If you have a README file with the description of your Emacs Lisp
package (which you definetely should have), you may as well want to use that file
as the canonical source of the documentation of the package. However, there is
another place which needs this documentation: the commentary section in
your main library file; you can update it manually, but it's tedious and error
prone (not to mention it's a violation of the [[https://en.wikipedia.org/wiki/Don't_repeat_yourself][DRY]] principle).

Org mode has built-in export facilities which can be used to convert Org documents
into various formats, including a simple plain text format (=ascii= backend).

This package employs these facilities to generate library headers from Org files
automatically; it may be used either from inside of Emacs or from the command line.

** Getting started

/Note/: these steps are written with assumption you're using [[https://github.com/cask/cask][Cask]] for project management.

0. [Optional] If you have installed =org-doc= manually (the only option at the moment), create a
   link to =org-doc=:

   #+begin_src bash
     $ cask link org-doc path/to/org-doc/installation
   #+end_src

1. Add =org-doc= to the development dependencies of your library:

   #+begin_src lisp
     (development
      (depends-on "org-doc"))
   #+end_src

   Fetch dependencies:

   #+begin_src bash
     $ cask install
   #+end_src

2. Put the [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html][library header]] boilerplate in your ELisp file.

3. Generate /Commentary/ section of the library headers:

   #+begin_src bash
     $ cask exec org-doc README.org your-package.el
   #+end_src

4. [Optional] Generate /Change Log/ section of the library headers:

   #+begin_src bash
     $ cask exec org-doc --section changelog CHANGELOG.org your-package.el
   #+end_src

5. Commit.

Run ~cask exec org-doc --help~ to see available options.

** Contributing                                                    :noexport:

*** Prerequisites

You need [[https://github.com/cask/cask][Cask]] installed (see [[http://cask.readthedocs.io/en/latest/guide/installation.html][docs]]).

*** Setup

Clone the repository:

#+begin_src bash
  $ git clone git@github.com:smaximov/org-doc.git
#+end_src

Install dependencies:

#+begin_src bash
  $ make dep-update
#+end_src

*** Preparing a pull request

Make sure all tests pass:

#+begin_src bash
  $ make test
#+end_src

Update package's commentary header if you have made changes to [[file:README.org][README.org]] (do not edit commentary by hand!):

#+begin_src bash
  $ make update-headers
#+end_src

Commit final changes and create a pull request, describing briefly what it does.

** Similar projects

- [[https://github.com/cute-jumper/org2elcomment][org2elcomment]] - provides an interactive function to update the commentary
  section of an Emacs Lisp file using the contents of an Org file opened in
  the current buffer.
- [[https://github.com/mgalgs/make-readme-markdown][make-readme-markdown]] - in contrast to =org-doc=, this package treats
  an Emacs Lisp file as the canonical source of documentation used to generate
  =README= in the Markdown format. Provides additional features like
  auto-detected badges and API documentation of public functions.

** License                                                         :noexport:

This program is distributed under the terms of GNU General Public License,
version 3 or any later version. See [[file:COPYING][COPYING]] for details.
